name: Devops-test
run-name: ${{ github.actor }} is doing devops test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '15'
      - name: Install dependencies npm install
        run: npm install 
      - name: Linter (ESLint) npm run lint
        run: npm run lint
      - name: Formatter (Prettier) npm run prettier
        run: npm run prettier 
      - name: Test (Jest) CI=true npm run test
        run: npm run test
      - name: Build npm run build
        run: npm run build
      

